config/routes.rb
Rails.application.routes.draw do
  resources :entries, only: [:new, :create, :show, :index, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @entry = Entry.new()
  end

  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to "/entries"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])

    if @entry.update(entry_params)
      redirect_to @entry
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy

    redirect_to entry_path, status: :see_other
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/edit.html.erb
<div class="edit-container">
<%= form_with model: @entry do |form| %>
<div class="title-input">
<%= form.label "Title:" %>
<%= form.text_field :title %>
</div>
<div class="body-input">
<%= form.label "Body:" %>
<%= form.text_field :body %>
</div>
<div class="submit">
<%= form.submit "Update Entry"%>
</div>
<% end %>

<%= link_to "Show all entries", "/entries" %>
</div>

app/views/entries/index.html.erb
<div class="header-container">
<h1>To Do</h1>
<%= link_to "New Entry", "/entries/new" %>
</div>


<ul>
  <% @entries.each do |entry| %>
  <div class="list-container">
  <div class="entries">
    <h1 class="entry-title"><%= link_to entry.title, entry %><h1>
    <h2 class="entry-body"><%= entry.body %><h2>
    <h3>Created at: <%= entry.created_at.to_formatted_s(:db)%></h3>
    <h4><%= link_to "Edit", edit_entry_path(entry) %>       <%= link_to "Delete", entry_path(entry), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></h4>
    </div>
    </div>
  <% end %>
</ul>

app/views/entries/new.html.erb
<div class="new-container">
<%= form_with model: @entry do |form| %>
<div class="title-input">
<%= form.label "Title:" %>
<%= form.text_field :title %>
</div>
<div class="body-input">
<%= form.label "Body:" %>
<%= form.text_field :body %>
</div>
<div class="submit">
<%= form.submit %>
</div>
<% end %>

<%= link_to "Show all entries", "/entries" %>
</div>

app/views/entries/show.html.erb
<h1><%= @entry.title %></h1>
<h2><%= @entry.body %></h2>

<%= link_to "Show all entries", "/entries" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'style.css' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>